### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by apjanke** [janklab/MlxShake#10]
I want a logo for this project! It should probably looks something like the Matlab logo, with an arrow pointing from it to a "document" icon. This would be used as the submission image on File Exchange, and in other places.

**Comment by ghost** [comment]
Would you like a specially designed vector icon?
Here's my past work on VSC:
https://github.com/PKief/vscode-material-icon-theme/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3ASNDST00M+

**Comment by apjanke** [comment]
Aw, heck yeah!

**Comment by ghost** [comment]
# Markdown-inspired icon?

![image](https://user-images.githubusercontent.com/82655227/134029913-45c6de75-b85b-4e68-a5d1-34ac1578d5bd.png)

**Comment by apjanke** [comment]
Ooooh, I dig it!

(That's the Matlab "L-Shaped Membrane" logo, flipped upside down, and in silhouette, as the second glyph, right?")

**Comment by ghost** [comment]
Yup!

**Comment by ghost** [comment]
https://uk.mathworks.com/matlabcentral/fileexchange/99274-mlxshake?s_tid=srchtitle

Still needs the logo updated to this logo!
