### ISSUE TITLE
External CLI command (like `exportmlx`) with `--format` option

### ISSUE THREAD

**Issue by ghost** [janklab/MlxShake#9]
I feel like a CLI top-level function would complete this.
It'd probably benefit from being a top level function `exportmlx`.
If it supported an `--extension` option with the `tex` or `md` values that would be great!

**Comment by apjanke** [comment]
LOL; already on the TODO list. ;)

![image](https://user-images.githubusercontent.com/2618447/133362230-9a224d2b-8d30-4f4c-a5b2-7315263b236a.png)

https://github.com/janklab/MlxShake/blob/master/doc-project/TODO.md

Thanks for making an Issue for it; most people probably aren't looking at the TODO.md file in the code.

I'll get this done pretty soon: it's not hard; just need to find an hour or two to put it together.

**Comment by apjanke** [comment]
It'll pick the format automatically based on the file extension of the output file you specified, defaulting to Markdown if no file extension is given, and will have a `--format` option to override that. Will have various other options that map to the other major configuration items in `MlxExportOptions`.

**Comment by apjanke** [comment]
Okay, here's a `mlxshake` shell command for you! It's in the new `bin/` directory.

https://github.com/janklab/MlxShake/commit/6174ef6832f7d2d92013f1db72cb9cef29cd290b

Try `./bin/mlxshake --help` to see its options.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/82655227/133416020-da95ac96-de1c-4f8f-a85f-a68575c2a8cb.png)
